---

spring:
  profiles:
    active: production
  application:
    name: cruncher

---

spring:
    profiles: development

server:
    port: 9001

---

spring:
    profiles: production
    main:
        banner-mode: "off"

github.enabled: true
github:
    baseUrl: 0
    accessToken: accessMeow